image: gitpod/workspace-full-vnc
# Update 7th September to reflect code base changes
ports:
- name: BTK API
  description: BlobToolKit API
  port: 8000
  visibility: public
- name: BTK Viewer
  description: BlobToolKit Viewer
  port: 8080
  visibility: public
- name: HiGlass
  description: The HiGlass port
  port: 8989
  onOpen: open-browser
  visibility: public

tasks:
  - name: Install HiGlass
  # https://docs.higlass.io/tutorial.html
    init: |
      cd /workspace/genome-note-publications
      
      pip install higlass-manage

      higlass-manage start

  - name: Install Nextflow
  # https://www.nextflow.io/docs/latest/getstarted.html
    init: |
      cd /workspace/genome-note-publications
      
      wget -qO- https://get.nextflow.io | bash

      chmod +x nextflow

      sudo mv nextflow /usr/local/bin

  - name: SETUP - btk install mamba and docker pull
    init: | 
      cd /workspace
      wget "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
      bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/mambaforge && rm Mambaforge-$(uname)-$(uname -m).sh
      /workspace/mambaforge/bin/mamba init bash

      source ${HOME}/.bashrc

      conda create -y -n btk -c conda-forge python=3.9

      cd /workspace
      git clone https://github.com/blobtoolkit/blobtoolkit btk_example

      DOCKERVERSION=latest
      docker pull genomehubs/blobtoolkit-api:$DOCKERVERSION
      docker pull genomehubs/blobtoolkit-viewer:$DOCKERVERSION
      gp sync-done step1
  
  - name: SETUP - docker run
    command: |
      gp sync-await step1
      API_PORT=8000
      PORT=8080
      VIEWERURL=$(gp url $PORT)
      APIURL=$(gp url $API_PORT)
      DOCKERVERSION=latest

      mkdir -p /workspace/logs

      docker rm -f btk-api-$API_PORT
      docker run -d \
      -u $UID:$GROUPS \
      --restart always \
      -p $API_PORT:8000 \
      -v /workspace/btk_example/src/data/example/:/blobtoolkit/datasets \
      -v /workspace/logs:/blobtoolkit/logs \
      -e BTK_API_PORT=8000 \
      -e BTK_API_URL=$APIURL/api/v1 \
      -e BTK_HTTPS=false \
      -e BTK_ORIGINS="$VIEWERURL http://localhost https://localhost null" \
      -e BTK_HOST=$VIEWERURL \
      -e BTK_USE_DEFAULT_LINKS=true \
      -e BTK_FILE_PATH=/blobtoolkit/datasets \
      -e BTK_ERROR_LOG=/blobtoolkit/logs/error.log \
      -e BTK_ACCESS_LOG=/blobtoolkit/logs/access.log \
      --name btk-api-$API_PORT \
      genomehubs/blobtoolkit-api:$DOCKERVERSION

      docker rm -f btk-viewer-$PORT
      docker run -d \
      --restart always \
      -p $PORT:8080 \
      -e BTK_API_URL=$APIURL/api/v1 \
      -e BTK_BASENAME=/view \
      -e BTK_GA_ID= \
      -e BTK_GDPR_URL= \
      -e BTK_MESSAGE= \
      --name btk-viewer-$PORT \
      genomehubs/blobtoolkit-viewer:$DOCKERVERSION && gp preview --external $VIEWERURL/view/all#Datasets 
      /workspace/mambaforge/bin/mamba init bash
      source ${HOME}/.bashrc

  - name: Install Genome Note Pipeline
  # https://github.com/sanger-tol/curationpretext
    init: |
      cd /workspace/genome-note-publications
      git clone -b 1.2.2 https://github.com/sanger-tol/genomenote.git
       gp sync-done step2

  - name: Pre-download some data
  # https://github.com/sanger-tol/curationpretext
    init: |
      mkdir -p /workspace/genome-note-publications/data
      cd /workspace/genome-note-publications/data
      wget https://tolit.cog.sanger.ac.uk/test-data/Epithemia_sp._CRS-2021b/assembly/release/uoEpiScrs1.1/insdc/GCA_946965045.1.fasta.gz
      gunzip GCA_946965045.1.fasta.gz
      wget https://tolit.cog.sanger.ac.uk/test-data/Epithemia_sp._CRS-2021b/genomic_data/uoEpiScrs1/pacbio/m64228e_220617_134154.ccs.bc1015_BAK8B_OA--bc1015_BAK8B_OA.rmdup.subset.bam
      wget https://tolit.cog.sanger.ac.uk/test-data/Epithemia_sp._CRS-2021b/genomic_data/uoEpiScrs1/pacbio/m64016e_220621_193126.ccs.bc1008_BAK8A_OA--bc1008_BAK8A_OA.rmdup.subset.bam
      wget https://tolit.cog.sanger.ac.uk/test-data/Epithemia_sp._CRS-2021b/analysis/uoEpiScrs1.1/read_mapping/hic/GCA_946965045.1.unmasked.hic.uoEpiScrs1.subsampled.cram
      wget https://tolit.cog.sanger.ac.uk/test-data/Epithemia_sp._CRS-2021b/analysis/uoEpiScrs1.1/read_mapping/hic/GCA_946965045.1.unmasked.hic.uoEpiScrs1.subsampled.bam

  - name: Open Tutorial Page
    init: |
      gp preview https://www.thebgacademy.org/BGA24/sessions/genome-note-publications-24

  - name: Install LibreOffice # VSCode extensions arn't working
    init: gp sync-await step2
    command: |
      sudo apt-get update && sudo apt-get install libreoffice -y
      gp sync-done step3

  - name: MAIN - TERMINAL TO USE
    # Installing click and ruff in the mamba environment didn't work for some reason
    # It is much easier to install via that mamba env's pip3
    # and then install pretext-to-tpf
    init: gp sync-await step3 # Wait for previous 'inits' to complete
    command: |
      cd /workspace
      
      source ${HOME}/.bashrc
      mamba activate btk

      pip3 install "blobtoolkit[full]"

      echo "WELCOME TO THE GENOME_NOTE_PUBLICATIONS SESSION!"
      

vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - codezombiech.gitignore # Language support for .gitignore files
    # - cssho.vscode-svgviewer                 # SVG viewer
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - shahilkumar.docxreader
    - EditorConfig.EditorConfig # override user/workspace settings with settings found in .editorconfig files
    - Gruntfuggly.todo-tree # Display TODO and FIXME in a tree view in the activity bar
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    # - nextflow.nextflow                      # Nextflow syntax highlighting
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
