image: gitpod/workspace-full-vnc
# Update 7th September to reflect code base changes

tasks:
  - name: Install Nextflow
  # https://www.nextflow.io/docs/latest/getstarted.html
    init: |
      cd /workspace/genome-note-publications
      
      wget -qO- https://get.nextflow.io | bash

      chmod +x nextflow

      sudo mv nextflow /usr/local/bin

  - name: SETUP - Mamba and conda env
    init: | 
      cd /workspace
      wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
      bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh
      /workspace/mambaforge/bin/mamba init bash

      source ${HOME}/.bashrc

      conda create -y -n genomenote -c conda-forge python=3.9

      gp sync-done conda
  
  - name: Install Genome Note Pipeline
  # https://github.com/sanger-tol/curationpretext
    init: |
      gp sync-await conda
      cd /workspace/genome-note-publications
      git clone -b 2.0.0 https://github.com/sanger-tol/genomenote.git
      gp sync-done pipeline

  - name: Pre-download some data
  # https://github.com/sanger-tol/curationpretext
    init: |
      mkdir -p /workspace/genome-note-publications/data
      cd /workspace/genome-note-publications/data
      wget https://tolit.cog.sanger.ac.uk/test-data/Ceramica_pisi/assembly/release/ilCerPisi1.1/insdc/GCA_963859965.1.fasta.gz
      wget https://tolit.cog.sanger.ac.uk/test-data/Ceramica_pisi/analysis/ilCerPisi1.1/read_mapping/hic/GCA_963859965.1.unmasked.hic.ilCerPisi2.subsampled.cram
      wget https://tolit.cog.sanger.ac.uk/test-data/Ceramica_pisi/genomic_data/ilCerPisi1/pacbio/m64097e_230309_154741.ccs.bc1012_BAK8A_OA--bc1012_BAK8A_OA.subsampled.bam
      wget https://tolit.cog.sanger.ac.uk/test-data/Ceramica_pisi/genomic_data/ilCerPisi1/pacbio/m84047_230817_174414_s3.ccs.bc2048.subsampled.bam
      

  - name: Open Tutorial Page
    init: |
      gp preview https://www.thebgacademy.org/BGA24/sessions/genome-note-24

  - name: Install LibreOffice # VSCode extensions arn't working
    command: |
      sudo apt install -y at-spi2-core
      sudo apt-get update && sudo apt-get install libreoffice -y

  - name: MAIN - TERMINAL TO USE
    # Installing click and ruff in the mamba environment didn't work for some reason
    # It is much easier to install via that mamba env's pip3
    # and then install pretext-to-tpf
    init: gp sync-await pipeline
    command: |
      cd /workspace/genome-note-publications
      
      source ${HOME}/.bashrc
      mamba activate genomenote

      echo "WELCOME TO THE GENOME_NOTE_PUBLICATIONS SESSION!"
      

vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - codezombiech.gitignore # Language support for .gitignore files
    - adamraichu.docx-viewer
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - EditorConfig.EditorConfig # override user/workspace settings with settings found in .editorconfig files
    - Gruntfuggly.todo-tree # Display TODO and FIXME in a tree view in the activity bar
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    # - nextflow.nextflow                      # Nextflow syntax highlighting
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
