image: gitpod/workspace-full-vnc
# Update 7th September to reflect code base changes
ports:
- name: something
  description: something
  port: 3000
  onOpen: open-browser
  visibility: public

tasks:
  - name: Install Nextflow
  # https://www.nextflow.io/docs/latest/getstarted.html
    init: |
      cd /workspace/treeval-curation/
      
      wget -qO- https://get.nextflow.io | bash

      chmod +x nextflow

      sudo mv nextflow /usr/local/bin

  - name: Install Genome Note Pipeline
  # https://github.com/sanger-tol/curationpretext
    init: |
      cd /workspace/treeval-curation/

      git clone -b 1.2.1 https://github.com/sanger-tol/genomenote.git

vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - codezombiech.gitignore # Language support for .gitignore files
    # - cssho.vscode-svgviewer                 # SVG viewer
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - eamodio.gitlens # Quickly glimpse into whom, why, and when a line or code block was changed
    - EditorConfig.EditorConfig # override user/workspace settings with settings found in .editorconfig files
    - Gruntfuggly.todo-tree # Display TODO and FIXME in a tree view in the activity bar
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    # - nextflow.nextflow                      # Nextflow syntax highlighting
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
